language: node_js
node_js:
  - 6.9.1
sudo: false
cache:
  directories:
    - node_modules
    - /^greenkeeper-.*$/
notifications:
  email:
    - torstenlink@gmx.de
    - markus.felten@gmx.de
before_install:
  - npm i -g npm@latest
before_script:
  - npm prune
  - npm install -g codecov
script:
  - npm run-script cover
after_script:
  - codecov
after_success:
  - npm run semantic-release
