language: node_js
node_js:
- iojs-v2
- iojs-v1
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email:
  - markus.felten@gmx.de
before_deploy:
- npm config set spin false --global
script: npm run-script cover
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
env:
  global:
    secure: RxbnJ1Urw5Y0AhpJ/MvlU3jeTndCanmFGLjac0ODCI3jaRbnsZZowytksXuoKYgeQjL4D68rtdcgZeGvft3aSzls2JK36d1xYkniHXr2AmuHPANBTiL0RCYIZJM0CtggRdIIFwEnhXvcsmfP79FsyquDh+7M6NC6uUE0R2YXKE6ewjnI4Ih+T1PS8/0Y85vjRSIq2WVSiHeQDC7gyHXO1CRzsYLZaZkkkEoXxFZmHX5pTzO2By64PunAhzQf5zQlefgKT/BiTtKNkfWbN1n2Z/+yl0m2ZLav7Ur3temq+GW+hfj6OmLlbdnH6fdSkCvUT8wONQcUk8uZn3zTuQy2JFnKiJw4avc6Lr0odH3Pl3puy2d9Rf9fGnKXJ/x8kO68fmJT0rq/1ca0Uj9rgI/88JajTbV6t/5LVA7jEG9EZVTwvLNeAgcvl3QJWLsao8sIryGXMSJjBa3Wk2DjWwAcsrXU359B493uXrlfbYRZdBzBBKp8dOhgjwNaqUMrW7NHtUovwGft6ZNkNOTzqRXGMcR5qNhEOmqB/sG7doTyTNYE2Xbrb/aphH9PvBMCQ2KaBLl2Dwti6z+Q056aEfIF+oeI0iqOhL3/6FoXtvEr/tjYc913r3RMJyyV+8znlQ0cny2BMpTLtzhRgHZ3US3OGGBelaM8+dxhs7ICu63mfp8=
deploy:
  provider: npm
  email: markus.felten@gmx.de
  skip_cleanup: true
  api_key:
    secure: kEfhgJEobDqMdIv0j5ppEVmza6yic4EBmxNIPzk64trXhrGpnyyqbBu+axldNpbzIdgoV9r5bj7vUl6S07F2TG0WbsU+nYfPWcixozGQS9RwDL7OZ3WG8bDPz9fN7VspvxPZxP8dKolM5oWuNH2Ke1A3ukKmLXJ78Tgg69zru7fsUkTGzY9mUez+Om3w3JgaymTZmkXhYWN9yHD+X5sqHnGbPRMaY9LGhSmf034yJ+Euk4CxVv4l3LGERilKMo6p3cgtY5L0serqwXcaQVoBNfHfgTtA38a6zFLapJ9yNVSBgijRLCnnl6KDjfI1Y/KC17XrIMidXdtfKfYo9jF1261I24Q9lM629v/0RrK+i78VzBiHc38xdBBDJBQNj4zjyebZxrd5MlqKhSknijnwdFnsWaTyu+y9c0aZvEwemxPBiFqSwez/H+ZRvZA78WC62Le6I2yV9M5ZvuaitSFlzH1OdQyBuLmNPzTOa+OtL4dDwYshsckPashPmDY2pArkTmpNaCSkHlyXDGyrsoE5zPWVNdR9pJFmXIPpnpn286B1OyaAbcPDGaixz2kw6a6Wdv3tQjlIB1kUJ8E6cnHajXQgmBmSseXDBhmWFExYwO896Waa9FYka3GeqB4Z+Njcnszcd4dtUFwbYPgT8tkqaHwUVpXJUIqOYoCZ7AFYsjI=
  on:
    branch: master
    repo: arlac77/uti
