language: node_js
node_js:
- iojs
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email:
  - markus.felten@gmx.de
before_deploy:
- npm config set spin false --global
script: npm run-script cover
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
env:
  global:
    secure: RxbnJ1Urw5Y0AhpJ/MvlU3jeTndCanmFGLjac0ODCI3jaRbnsZZowytksXuoKYgeQjL4D68rtdcgZeGvft3aSzls2JK36d1xYkniHXr2AmuHPANBTiL0RCYIZJM0CtggRdIIFwEnhXvcsmfP79FsyquDh+7M6NC6uUE0R2YXKE6ewjnI4Ih+T1PS8/0Y85vjRSIq2WVSiHeQDC7gyHXO1CRzsYLZaZkkkEoXxFZmHX5pTzO2By64PunAhzQf5zQlefgKT/BiTtKNkfWbN1n2Z/+yl0m2ZLav7Ur3temq+GW+hfj6OmLlbdnH6fdSkCvUT8wONQcUk8uZn3zTuQy2JFnKiJw4avc6Lr0odH3Pl3puy2d9Rf9fGnKXJ/x8kO68fmJT0rq/1ca0Uj9rgI/88JajTbV6t/5LVA7jEG9EZVTwvLNeAgcvl3QJWLsao8sIryGXMSJjBa3Wk2DjWwAcsrXU359B493uXrlfbYRZdBzBBKp8dOhgjwNaqUMrW7NHtUovwGft6ZNkNOTzqRXGMcR5qNhEOmqB/sG7doTyTNYE2Xbrb/aphH9PvBMCQ2KaBLl2Dwti6z+Q056aEfIF+oeI0iqOhL3/6FoXtvEr/tjYc913r3RMJyyV+8znlQ0cny2BMpTLtzhRgHZ3US3OGGBelaM8+dxhs7ICu63mfp8=
deploy:
  provider: npm
  email: markus.felten@gmx.de
  skip_cleanup: true
  api_key:
    secure: dMBbFmVUokhgja/EAMcz8LBIUHNdcV2isl3vL9b3LoJb8KsLBid98eXZ1CFmRnKTIJ5rRe4XorjzRwb18vlwZvGG5my3DcmKhozlZ2EAVDzfWUQP4I74Be9St3D/eAPyu9C2t+WcxwuopT7uUYwC3PD38udidQjU98L2r6UeNsG8GYEjh9Z4a5p4UGoNqtedx08HrZIZwb5N1DWdElId0AC9Mz5ZsQ9UYwmg5oQtrhGMxg362OJvMQh4URXnQH4EZfavqjVgGDOpFhRrsfV1+29RpVLBQeIWhbisAiA3LBBhoLWgEyfrcW/m14vgvS29H85YnZAqO58slTbYflH+5O6uUyap3zdposN6cEV2wFrlS5qmlJ17Z8mjaUqwJmGQOb4i80p7HUAKcEYNiC8oruMxKSSaOCWz3TNOxejq2/n7A3i9BHPrjGiQoNjbYrRJOHdyOVw/UNUaS8fVsSqu8/tSGe+NWQyLQLfGJ+2Wczi97jv8Tu2f+4w1cHW9M+4AeuMYC4LkbHwHZTY77n/2H9m7/JzwD3ncvqmBC8PUDAFD5RbEAb2301yO4JPURp2uZRSjDQ7mB61kincmJeHNPiu5hksBEsCxxAjrhfGlvhMKUcL9rEmNt7E/eERdDXoCgXuFtMImt0mxfyVWYa7cIjk63So702G3u6+Z8tqa8MI=
  on:
    branch: master
    repo: arlac77/uti
