language: node_js
node_js:
  - 10.13
sudo: 'false'
cache: npm
notifications:
  email:
    - markus.felten@gmx.de
before_install:
  - npm i -g npm@latest
before_script:
  - npm prune
  - npm install -g --production coveralls codecov
script:
  - npm run cover
  - npm run lint
  - npm run docs
after_script:
  - codecov
  - cat ./coverage/lcov.info | coveralls
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
