language: node_js
node_js:
  - 7.7.4
  - 6.10.0
sudo: false
cache:
  directories:
    - node_modules
notifications:
  email:
    - markus.felten@gmx.de
before_install:
  - npm i -g npm@latest
before_script:
  - npm prune
  - npm install -g codecov
  - npm install coveralls
script:
  - npm run cover
after_script:
  - codecov
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run docs
after_success:
  - npm run semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
