language: node_js
node_js:
  - 10.15.3
  - 12.0.0
cache: npm
script:
  - npm run cover
branches:
  only:
    - master
    - /^greenkeeper/.*$/
jobs:
  include:
    - stage: docs
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm install -g --production coveralls codecov
        - npm run cover
        - codecov
        - cat ./coverage/lcov.info | coveralls
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: 'true'
        script:
          - npx semantic-release
