language: node_js
node_js:
  - "iojs"

notifications:
  email:
    - markus.felten@gmx.de

script: "npm run-script cover"

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
