on: pull_request_target
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - if: github.actor == 'dependabot[bot]'
        uses: hmarr/auto-approve-action@v4.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: Auto approved automated PR
name: Auto approve
