on:
  pull_request:
    branches:
      - master
      - next
  push:
    branches:
      - master
      - next
permissions:
  contents: read
jobs:
  finish:
    needs:
      - test-node
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          path-to-lcov: build/coverage/lcov.info
  release:
    needs:
      - test-node
      - test-browser
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: 20.11.1
      - run: npm ci
      - env:
          CI: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
  test-browser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - chrome
          - firefox
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: 20.11.1
      - run: npm ci
      - env:
          BROWSER: ${{ matrix.browser }}
        run: npm run test:browser-ava --if-present
      - run: npx playwright install
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 20.11.1
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - continue-on-error: true
        name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-${{ matrix.test_number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: build/coverage/lcov.info
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run cover --if-present
name: CI
