on: pull_request_target
jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/pr_labeler.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: false
name: Pull Request Labeler
